name: Lint and SAST

on:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/actions/linter_ruby.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  sast:
    uses: ./.github/actions/sast_ruby.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
